### ISSUE TITLE
Porting to Vue3

### ISSUE THREAD

**Issue by beres** [bytefury/spacewind#22]
Hi,

Do you have any roadmap to vue3?

**Comment by jonathanpmartins** [comment]
Hey @mohitpanjwani ,
If you have plans to migrate to Vue3, feel free to use the brand new [`v-money3`](https://www.npmjs.com/package/v-money3).
The Vue Mask for Vue3!

**Comment by mohitpanjwani** [comment]
Hi @jonathanpmartins, I am working on it as we speak. 

Thanks for the suggestion. ✌️

**Comment by mohitpanjwani** [comment]
> Hi,
> 
> Do you have any roadmap to vue3?

Upgrading to Vue3 is a lot of work and with the release of Headless UI, it no longer makes sense to use Spacewind anymore. 

We will be replacing Spacewind components in favor of Accessible components powered by TailwindUI and HeadlessUI.
